"""add

Revision ID: 7fc8cb49dbbc
Revises: c3d8c3fc03a3
Create Date: 2023-01-28 14:10:36.324453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc8cb49dbbc'
down_revision = 'c3d8c3fc03a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_hotels', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_column('best_hotels')

    # ### end Alembic commands ###
