"""add

Revision ID: 814ccb3043ea
Revises: 5fc73e1584a7
Create Date: 2023-01-29 09:05:14.926303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814ccb3043ea'
down_revision = '5fc73e1584a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['rating'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
